export const SELECT_TOP_STORIES  = 'SELECT_TOP_STORIES';
export const TOP_STORIES_START   = 'TOP_STORIES_START';
export const TOP_STORIES_SUCCESS = 'TOP_STORIES_SUCCESS';
export const TOP_STORIES_FAILURE = 'TOP_STORIES_FAILURE';

export const MOST_POPULAR_START   = 'MOST_POPULAR_START';
export const MOST_POPULAR_SUCCESS = 'MOST_POPULAR_SUCCESS';
export const MOST_POPULAR_FAILURE = 'MOST_POPULAR_FAILURE';
